Feature/myc 138
Sphereon-Opensource/mnemonic-seed-generator-plugin pull request #1
Opened 2021-12-09 15:52 UTC by maikel-maas

2021-12-09 19:52 UTC, nklomp requested changes
See remarks.

BTW I think we need to add something to our DoD:
Ensure the plugin can generate a seed using the example screen in React-Native

2021-12-09 19:52 UTC, nklomp commented on README.md
> +A Veramo plugin to generate and store mnemonic pass phrases and seeds
Please make this in line with the styling of our other repos/plugins

2021-12-09 19:52 UTC, nklomp commented on README.md
> +To run the tests a VC_HTTP_API_AUTH_TOKEN environment variable needs to be present with an authorization token.
Why?

2021-12-09 19:52 UTC, nklomp commented on .eslintrc.json
> +{
Please put this in the SSI-SDK monorepo not in a seperate repo!

2021-12-09 19:52 UTC, nklomp commented on src/agent/MnemonicSeedGenerator.ts
> +  private async generateMnemonic(args: IMnemonicGeneratorArgs): Promise<string> {
I think returning an array of strings for the words makes more sense. 
First of all it means it is order. It also means any user doesn't have to do manual splitting and trimming. We should have done that. Lastly it means there is a quick check on the amount of items possible

2021-12-09 19:52 UTC, nklomp commented on src/agent/MnemonicSeedGenerator.ts
> +    const seed = await this.getSeed({ name: args.name, sha256: args.sha256 });
I think id betters fits than name for a mnemonic

2021-12-09 19:52 UTC, nklomp commented on src/agent/MnemonicSeedGenerator.ts
> +    let valid = true;
Why do we start out with a valid=true assertion? Never do that when checking something sensitive. In this case without providing a mnemonic it would return true. Fortunately in this case it is not exploitable

2021-12-09 19:52 UTC, nklomp commented on src/agent/MnemonicSeedGenerator.ts
> +        if (i > highestIndex) {
Although this algorithm sort of gets the job done, it would also return true if I only provide a partial menmonic.

The algo needs to check for the exact words being identical in the exact order for the exact same amount of words.

2021-12-09 19:52 UTC, nklomp commented on src/agent/MnemonicSeedGenerator.ts
> +  private async generateMnemonic(args: IMnemonicGeneratorArgs): Promise<string> {
I think it would also make sense to have an optional argument to immediately save the mnemonic

2021-12-09 19:52 UTC, nklomp commented on src/agent/MnemonicSeedGenerator.ts
> +    if (args.name && args.seed && args.mnemonic && this.secretBox) {
Is there a reason we need the seed? We can always recreate the seed from the mnemonic.

2021-12-09 19:52 UTC, nklomp commented on src/agent/MnemonicSeedGenerator.ts
> +      const seed = new Seed();
The name is a bit confusing, given it contains more than a seed. And as mentioned, probably this should be more about the mnemonic to begin with. The same comment applies to that. Something like MnemonicInfo makes more sense to me

2021-12-09 19:52 UTC, nklomp commented on src/agent/entity/seed.ts
> +export class Seed {
MnemonicInfo

2021-12-09 19:52 UTC, nklomp commented on src/agent/entity/seed.ts
> +  @PrimaryColumn({ name: 'name' })
id

2021-12-09 19:52 UTC, nklomp commented on src/types/IMnemonicSeedGenerator.ts
> +  name?: string;
name to id -> if no id would be supplied we need to generate a unique id ourselves, probably using the same value as the hash might make sense

2021-12-09 19:52 UTC, nklomp commented on agent.yml
> +    - save
This doesn't match the method names. The method names are more correct, since they are more descriptive. As part of Veramo you have to be aware that you basically can bundle/bind multiple plugins into 1 agent. Meaning you want to stay away from potential method name clashes

2021-12-10 15:47 UTC, maikel-maas commented on .eslintrc.json
> +{
Ok! I'll close that PR and open another one.

2021-12-10 15:47 UTC, maikel-maas commented on README.md
> +To run the tests a VC_HTTP_API_AUTH_TOKEN environment variable needs to be present with an authorization token.
My mistake I used that project as template.

2021-12-10 15:47 UTC, maikel-maas commented on agent.yml
> +    - save
I changed the method names because the plugins can be bunded. I just forgot to update this file.

2021-12-10 15:47 UTC, maikel-maas commented on src/agent/MnemonicSeedGenerator.ts
> +  private async generateMnemonic(args: IMnemonicGeneratorArgs): Promise<string> {
Fixed!

2021-12-10 15:48 UTC, maikel-maas commented on src/agent/MnemonicSeedGenerator.ts
> +    let valid = true;
if the mnemonic does not exist it throws an exception. Anyway, I'm returning it right away now.

2021-12-10 15:48 UTC, maikel-maas commented on src/agent/MnemonicSeedGenerator.ts
> +    const seed = await this.getSeed({ name: args.name, sha256: args.sha256 });
Fixed!

2021-12-10 15:48 UTC, maikel-maas commented on src/agent/MnemonicSeedGenerator.ts
> +        if (i > highestIndex) {
The ticket says: "Verify a mnemonic against a previously generated seed. Idealy we can pas in a index-word value map to verify, so that we can support verification for instance of lets say 5 words out of 12". We already have a library that validates a mnemonic for a perfect match. I will use that one.

2021-12-10 15:48 UTC, maikel-maas commented on src/agent/MnemonicSeedGenerator.ts
> +    if (args.name && args.seed && args.mnemonic && this.secretBox) {
Removed!

2021-12-10 15:48 UTC, maikel-maas commented on src/agent/MnemonicSeedGenerator.ts
> +      const seed = new Seed();
Fixed!

2021-12-10 15:48 UTC, maikel-maas commented on src/agent/entity/seed.ts
> +export class Seed {
Fixed!

2021-12-10 15:48 UTC, maikel-maas commented on src/agent/entity/seed.ts
> +  @PrimaryColumn({ name: 'name' })
Fixed!

2021-12-10 15:48 UTC, maikel-maas commented on src/types/IMnemonicSeedGenerator.ts
> +  name?: string;
Done!

2021-12-10 16:10 UTC, maikel-maas commented on README.md
> +A Veramo plugin to generate and store mnemonic pass phrases and seeds
Will be updated in SSI-SDK

2021-12-10 22:07 UTC, nklomp requested changes
Same last small remarks, which can be fixed in the monorepo

2021-12-10 22:07 UTC, nklomp commented on src/agent/MnemonicInfoGenerator.ts
> +    if (args.shouldSave) {
suggest to simply rename to persist. Should suggests that the outcome could also be that it won't be stored even if you pass in true

2021-12-10 22:07 UTC, nklomp commented on src/types/IMnemonicInfoGenerator.ts
> +  shouldSave?: boolean;
suggest to simply rename to persist. Should suggests that the outcome could also be that it won't be stored even if you pass in true

2021-12-10 22:11 UTC, nklomp commented on src/agent/MnemonicSeedGenerator.ts
> +        if (i > highestIndex) {
Yes, probably makes sense to create another method to verify a partial mnemonic argument.
But then the use really has to provide the correct index-word combination matching the index-word in the stored mnemonic.

Let's say the DB has 12 words in the mnemonic and let's say that a wallet wants the user to supply the words at position 3, 9 and 11. Then the method should check the exact words in the DB at positions 3, 9 and 11 to match what is in the DB.

2021-12-10 22:13 UTC, nklomp commented
> Same last small remarks, which can be fixed in the monorepo

BTW, I do thing we need the following (from a comment on the mnemonic check code):
Probably makes sense to create another method to verify a partial mnemonic argument.
But then the user really has to provide the correct index-word combination matching the index-word in the stored mnemonic.

Let's say the DB has 12 words in the mnemonic and let's say that a wallet wants the user to supply the words at position 3, 9 and 11. Then the method should check the exact words in the DB at positions 3, 9 and 11 to match what is in the DB.

2021-12-13 13:59 UTC, maikel-maas commented on src/types/IMnemonicInfoGenerator.ts
> +  shouldSave?: boolean;
Fixed!

2021-12-13 13:59 UTC, maikel-maas commented on src/agent/MnemonicInfoGenerator.ts
> +    if (args.shouldSave) {
Fixed!

2021-12-13 14:07 UTC, maikel-maas commented
@nklomp All changes are on the ssi-sdk PR

2021-12-13 23:18 UTC, nklomp commented on src/types/IMnemonicInfoGenerator.ts
> +  shouldSave?: boolean;
remove 'should', but mentioned that in the other PR, so closing it here.

2021-12-13 23:19 UTC, nklomp commented on src/agent/MnemonicInfoGenerator.ts
> +    if (args.shouldSave) {
remove 'should', but mentioned that in the other PR, so closing it here.

2021-12-13 23:19 UTC, nklomp commented
Closing this one, as we moved the PR over to the SSI-SDK repo

2021-12-13 23:19 UTC, closed without merging